### PR TITLE
feat: xlsx file storing to database

### PR DESCRIPTION
**Pull request by Insta-x**
### Changes Made:

- Added storing XLSX file to database.
- Added data type to be used in the SQL retriever prompting.

### Tests:

- Added unit tests to verify XLSX file is stored properly to the database.
- Changed some tests to accommodate the modified `get_table_schema` that includes column data types.

### CODE REVIEW

**Comment by TakeMeGH** [comment]
SonarCloud suggests fixing an issue in the commented code.

**Comment by jasonirvine76** [comment]
LGTM

**Comment by nyoosteven** [comment]
Glad to hear it’s looking good! Now that we have the parsing code set up for CSV, TXT, XLSX, and PDF, Let's discuss next week for the RAG process.

**Comment by nyoosteven** [comment]
Looks Good to me!

**Pull request merged**
