### PR TITLE
Add Generate Slug and Check If Slug Exist

### PR DESCRIPTION
**Pull request by jasonirvine76**
### Changes Made:

**Check if slug exists**
- Implemented a method to verify if a given slug is already in use before creating or updating a chatbot.

**Add generated slug in the front end**
- Updated the frontend to automatically generate and display a slug based on the chatbot name input

**Add unit test for checking slug**
- Added unit tests to ensure the functionality for checking slug existence works correctly and handles various scenarios, including cases where slugs are already taken.

### CODE REVIEW

**Comment by TakeMeGH** [comment]
Is the automatically generated slug able to update in real-time when the user types the name of the bot?

**Comment by jasonirvine76** [comment]
> Is the automatically generated slug able to update in real-time when the user types the name of the bot?

Yes, it's supposed to update in real-time for create not for edit

**Comment by TakeMeGH** [comment]
> > Is the automatically generated slug able to update in real-time when the user types the name of the bot?
> 
> Yes, it's supposed to update in real-time for create not for edit

So, what is the rule applied to convert a character into a "-"?

**Comment by jasonirvine76** [comment]
> > > Is the automatically generated slug able to update in real-time when the user types the name of the bot?
> > 
> > 
> > Yes, it's supposed to update in real-time for create not for edit
> 
> So, what is the rule applied to convert a character into a "-"?

These 2 rules
.replace(/\s+/g, '-')      
.replace(/--+/g, '-');

**Pull request merged**
