### PR TITLE
feat: Create Document automation to relevant storage

### PR DESCRIPTION
**Pull request by nyoosteven**
This PR introduces enhancements that automate the process of transferring documents from S3 storage to the relevant database. It simplifies and streamlines the document processing pipeline, ensuring efficiency and scalability in handling structured and unstructured data.

- S3 Document Fetching
- Document Type-Based Processing
- Automated Metadata Management
- Tabular Data Storage
- Vectorized Content Storage

### CODE REVIEW

**Review by arkanalexei — COMMENTED** [review]
Please address the code smells in your PR

**Comment by nyoosteven** [comment]
@Insta-x Don't forget to handle the issues also ya. Thanks !

**Comment by nyoosteven** [comment]
Can someone identify this issue? what is this dude?

**Comment by Insta-x** [comment]
@nayyara-airlangga can you help with this migration issue again? 😄

**Pull request merged**
