### PR TITLE
Add Centralized Logging

### PR DESCRIPTION
**Pull request by Veivel**
## Summary

Here's a fun one – in this PR I implement self-hosted, centralized logging for all our docker containers using Promtail and VictoriaLogs. This is to allow any developer to view and monitor the logs and errors in real-time, without having to SSH to staging (or prod) every time. The logs server can be accessed on `{HOST}:9428/select/vmui`. Login credentials should be in `.env`. See changes on `development.md` for more info on how to use.

## Changes
- `.env.example`
-  added `dev.v2.docker-compose.yml` for end-to-end dockerization (simulate staging/prod) with victoria logs and vector db (basically with this docker compose you won't need to boot up 2 different docker composes to develop locally)
- added config files in `config/` for promtail and vmauth
 - edited `infra/stg/docker-compose.yml` to add 3 new services (victorialogs, promtail, and vmauth) which will run alongside our db and app.
 
 ## How the logging works now
 
Essentially, we use Promtail as an agent to collect the logs (from docker). Promtail pushes the logs to VictoriaLogs, which stores it, and allows you to view or query from it on its webserver. VMAuth (VictoriaMetrics Auth) functions as a proxy which in this case will simply ask for credentials (Basic Auth format) before routing you to VictoriaLogs.

## NOT implemented

- `test_config` tests for VMAUTH environment variables, since they are not used inside the actual app.
- VMAuth proxy for VictoriaMetrics (only logs for now)
- `dev.docker-compose.yml`

### CODE REVIEW

**Comment by nayyara-airlangga** [comment]
Not gonna comment much on the implementations. But have you tested this for when the application is ran in Docker?

**Comment by Veivel** [comment]
> Not gonna comment much on the implementations. But have you tested this for when the application is ran in Docker?

Yes, that's why I supplied the `dev.v2.docker-compose.yml`.

**Comment by nayyara-airlangga** [comment]
> > Not gonna comment much on the implementations. But have you tested this for when the application is ran in Docker?
> 
> 
> 
> Yes, that's why I supplied the `dev.v2.docker-compose.yml`.

@Veivel Looks good to me then. Approved

**Review by nayyara-airlangga — APPROVED** [review]

**Comment by Veivel** [comment]
> > > Not gonna comment much on the implementations. But have you tested this for when the application is ran in Docker?
> > 
> > 
> > Yes, that's why I supplied the `dev.v2.docker-compose.yml`.
> 
> @Veivel Looks good to me then. I originally had a nit on why use promtail instead of vmagent but this is good enough. Approved

Alright. For future reference can you explain your nit – is it because vmagent can also collect metrics while promtail only does logs?

**Pull request merged**
