### PR TITLE
refactor navbar

### PR DESCRIPTION
**Pull request by Veivel**
## Summary

As long ago (see [SAP-55](https://linear.app/sapujagad-id/issue/SAP-55/refactor-navbar-from-bot-module)) discussed the navbar needed to be refactored to another directory/module. Additionally we had issues with having to fetch `admin_emails` from the config on every appearance of the navbar, as summarized in [SAP-74](https://linear.app/sapujagad-id/issue/SAP-74/refactor-navbar-role-check).

## Changes

this PR completes two stories:
- refactor navbar to not be in bot module
- change admin checking in the navbar to be purely front-end (cookie-based) instead of having to fetch from the config
- additionally: removed all unnecessary dependency injections that are no longer needed after fixing the admin_email fetching
- additionally: fixed all unit tests affected by changes above

### Implementation: Cookie-based checking for admin

I preface this with the fact that we do have auth on the page access itself, and that the navbar is NOT for security. 

image

But we want the user to know what modules they have access to. But it's pretty simple: when the user logs in, we save `is_admin` cookie (True or False). The navbar now shows links to the admin modules only when `is_admin` == `True`.

The actual authorization on pages like `/users` are NOT changed. Therefore, no security issue here.

### CODE REVIEW

**Comment by TakeMeGH** [comment]
It seems like an admin and a user will have different pages that can be accessed. Can we test if the role is a normal user?

**Comment by Veivel** [comment]
> It seems like an admin and a user will have different pages that can be accessed. Can we test if the role is a normal user?

Sure, I'll make another commit and let you know

**Review by jasonirvine76 — APPROVED** [review]
LGTM :)

**Comment by jasonirvine76** [comment]
just need to fix the conflict

**Comment by Veivel** [comment]
> It seems like an admin and a user will have different pages that can be accessed. Can we test if the role is a normal user?

Hey @TakeMeGH I'll add another story for this, it does seem like it'll take a bit extra effort to do that unit test.

**Comment by TakeMeGH** [comment]
> > It seems like an admin and a user will have different pages that can be accessed. Can we test if the role is a normal user?
> 
> Hey @TakeMeGH I'll add another story on Linear for this, it does seem like it'll take a bit extra effort to do that unit test.

Sure :D

**Comment by Veivel** [comment]
Let the records show that I force-pushed to this branch in an emergency, after trying to make the `git rebase` work instead of merging like normal. No significant changes after the PR approval was made.

**Pull request merged**
