### PR TITLE
[SPN-9] Setup Slack app to run code

### PR DESCRIPTION
**Pull request by nayyara-airlangga**
This change enables us to handle Slack events and slash commands. The details are as follows

- Setup Slack SDK and basic config tests
- Setup base event handler
- Setup base Slack adapter

### CODE REVIEW

**Comment by nayyara-airlangga** [comment]
Regarding the coverage, it's safe to ignore it for the time being since it's mostly just initialization logic for the time being which can't be tested either way

**Review by TakeMeGH — COMMENTED** [review]
It looks like the code is fine, but could you explain the development flow using ngrok? Because as far as I know, we need to input the ngrok link into the Slack app, right? If that's the case, how can multiple people develop this bot while having different ngrok links on different laptops?

**Comment by jasonirvine76** [comment]
Looks good, i dont see any issues with the code

**Comment by nayyara-airlangga** [comment]
> It looks like the code is fine, but could you explain the development flow using ngrok? Because as far as I know, we need to input the ngrok link into the Slack app, right? If that's the case, how can multiple people develop this bot while having different ngrok links on different laptops?

@TakeMeGH You have a good point. I haven't found a simple way to allow parallel development since Slack only allows for one Request Url for a given time. For now, it seems we will have to coordinate around this

**Comment by nayyara-airlangga** [comment]
@TakeMeGH , a slash command can have differing slash commands from each other. Since you'll be handling Ask command, I think we won't conflict

**Review by TakeMeGH — APPROVED** [review]
okay, I just want to make sure that there are no issues related to that. Alright, thank you.

**Comment by nayyara-airlangga** [comment]
Will merge then. Thank you

**Pull request merged**
