### PR TITLE
test: patch open ai api key in valid config test

### PR DESCRIPTION
**Pull request by nayyara-airlangga**

### CODE REVIEW

**Comment by nayyara-airlangga** [comment]
Sounds

**Review by arkanalexei — APPROVED** [review]
images

**Comment by nayyara-airlangga** [comment]
Good

**Comment by nayyara-airlangga** [comment]
To

**Comment by nayyara-airlangga** [comment]
Me

**Comment by nyoosteven** [comment]
Sounds Good to me!

**Comment by jasonirvine76** [comment]
Nice, very cool!

**Review by jasonirvine76 — APPROVED** [review]

**Comment by Veivel** [comment]
Amazing!

**Comment by Insta-x** [comment]
Making the test shorter and including all the AppConfig in one function. Don't see a problem with this code.

**Pull request merged**
