### PR TITLE
feat: Support for Processing TXT Files

### PR DESCRIPTION
**Pull request by nyoosteven**
* This PR refactors the existing TXTProcessor to support multiple TXT File
* This PR also include storing and loading TXT File into vector database

### CODE REVIEW

**Comment by jasonirvine76** [comment]
lgtm

**Comment by nyoosteven** [comment]
Glad to hear it’s looking good! Now that we have the parsing code set up for CSV, TXT, XLSX, and PDF, Let's discuss next week for the RAG process.

**Comment by arkanalexei** [comment]
> Glad to hear it’s looking good! Now that we have the parsing code set up for CSV, TXT, XLSX, and PDF, Let's discuss next week for the RAG process.

I agree. We should start first by talking to the Broom folks for access to their database, though.

**Review by arkanalexei — APPROVED** [review]

**Review by Insta-x — APPROVED** [review]
Doesn't seem to be any problem here. LGTM!

**Pull request merged**
