### PR TITLE
feat: add fetch and integration of negative reaction for analytics dashboard

### PR DESCRIPTION
**Pull request by jasonirvine76**
This PR implements the negative reaction API:

Fetch Negative Reaction Data:
- Created an API/service to retrieve stored negative reactions 
- Created unit tests for fetch negative reactions API

### CODE REVIEW

**Comment by TakeMeGH** [comment]
I think this task already handled 😂

**Comment by arkanalexei** [comment]
> I think this task already handled 😂

Is this for real

**Comment by Veivel** [comment]
> I think this task already handled 😂

😨😨😨

**Comment by jasonirvine76** [comment]
Haha, abdul told me that this task already handled 😂

**Pull request closed without merging**
