### PR TITLE
feat: add presigned url for docs

### PR DESCRIPTION
**Pull request by jasonirvine76**
### Presigned URL Method for Documents
- Added a method to generate presigned URLs for S3-stored documents, allowing temporary access to document files.
- Added function in utils.py to generate presigned URLs from DocumentModel

### Endpoint Configuration in S3 Client Initialization
- Configured the S3 client to use the appropriate AWS endpoint URL, addressing issues related to region constraints (e.g., ap-southeast-3).
- Ensures that the presigned URL points to the correct regional endpoint.

### Unit Tests for Presigned URL
- Added tests for the presigned URL
- Configured test settings to include the correct endpoint URL

### CODE REVIEW

**Comment by Veivel** [comment]
@jasonirvine76 So one of the things I wanted to do (I assumed this was my story and didn't tell you) was that this needs to be refactored. Currently `repository` returns a DocumentModel (sqlalchemy) which is **NOT** a Document (basemodel). This means running this code would return:

```
    print("url: " + documents[0].generate_presigned_url(client, aws_config.aws_public_bucket_name))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DocumentModel' object has no attribute 'generate_presigned_url'
```

I think this calls for a refactor of the `generate_presigned_url` function. What do you think?

**Comment by Veivel** [comment]
If you agree jason, please don't wait for my delayed response any longer and make the changes ASAP since @nyoosteven has been waiting for this functionality for the past two week.

**Review by Veivel — CHANGES_REQUESTED** [review]
move `generate_presigned_url` function

**Comment by jasonirvine76** [comment]
> @jasonirvine76 So one of the things I wanted to do (I assumed this was my story and didn't tell you) was that this needs to be refactored. Currently `document/repository.py` returns a `DocumentModel` (sqlalchemy) which is **NOT** a `Document` (basemodel). This means running this code would return:
> 
> ```
>     print("url: " + documents[0].generate_presigned_url(client, aws_config.aws_public_bucket_name))
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'DocumentModel' object has no attribute 'generate_presigned_url'
> ```
> 
> I think this calls for a refactor of the `generate_presigned_url` function. What do you think?

Ah yes, when I tested it, it needs to parse DocumentModel to Document.

**Comment by jasonirvine76** [comment]
> If you agree jason, please don't wait for my delayed response any longer and make the changes ASAP since @nyoosteven has been waiting for this functionality for the past two weeks.
> 
> That's also one thing to consider when refactoring, I think it should be a `lib` or `utils` function (if possible) so the RAG team can have a much simpler dependency injection when trying to call this method anywhere they wish

Alright, will fix this ASAP

**Pull request merged**
